# Data Cleaning

Clean missing values, types, duplicates, and invalid measurements.

In [1]:
import pandas as pd
import numpy as np
# Load a raw dataset here.

In [2]:
df = pd.read_csv("../data/raw/city_day.csv")

df.head()

,City,Date,PM2.5,PM10,NO,NO2,NOx,NH3,CO,SO2,O3,Benzene,Toluene,Xylene,AQI,AQI_Bucket
0,Ahmedabad,2015-01-01,NaN,NaN,0.92,18.22,17.15,NaN,0.92,27.64,133.36,0.00,0.02,0.00,NaN,NaN
1,Ahmedabad,2015-01-02,NaN,NaN,0.97,15.69,16.46,NaN,0.97,24.55,34.06,3.68,5.50,3.77,NaN,NaN
2,Ahmedabad,2015-01-03,NaN,NaN,17.40,19.30,29.70,NaN,17.40,29.07,30.70,6.80,16.40,2.25,NaN,NaN
3,Ahmedabad,2015-01-04,NaN,NaN,1.70,18.48,17.97,NaN,1.70,18.59,36.08,4.43,10.14,1.00,NaN,NaN
4,Ahmedabad,2015-01-05,NaN,NaN,22.10,21.42,37.76,NaN,22.10,39.33,39.31,7.01,18.89,2.78,NaN,NaN

In [3]:
df["Date"] = pd.to_datetime(df["Date"])

In [4]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 29531 entries, 0 to 29530
Data columns (total 16 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   City        29531 non-null  str
 1   Date        29531 non-null  datetime64[us]
 2   PM2.5       24933 non-null  float64
 3   PM10        18391 non-null  float64
 4   NO          25949 non-null  float64
 5   NO2         25946 non-null  float64
 6   NOx         25346 non-null  float64
 7   NH3         19203 non-null  float64
 8   CO          27472 non-null  float64
 9   SO2         25677 non-null  float64
 10  O3          25509 non-null  float64
 11  Benzene     23908 non-null  float64
 12  Toluene     21490 non-null  float64
 13  Xylene      11422 non-null  float64
 14  AQI         24850 non-null  float64
 15  AQI_Bucket  24850 non-null  str
dtypes: datetime64[us](1), float64(13), str(2)
memory usage: 3.6 MB

In [5]:
df = df.sort_values(["City" , "Date"]).reset_index(drop = True)

In [6]:
df.head()

,City,Date,PM2.5,PM10,NO,NO2,NOx,NH3,CO,SO2,O3,Benzene,Toluene,Xylene,AQI,AQI_Bucket
0,Ahmedabad,2015-01-01,NaN,NaN,0.92,18.22,17.15,NaN,0.92,27.64,133.36,0.00,0.02,0.00,NaN,NaN
1,Ahmedabad,2015-01-02,NaN,NaN,0.97,15.69,16.46,NaN,0.97,24.55,34.06,3.68,5.50,3.77,NaN,NaN
2,Ahmedabad,2015-01-03,NaN,NaN,17.40,19.30,29.70,NaN,17.40,29.07,30.70,6.80,16.40,2.25,NaN,NaN
3,Ahmedabad,2015-01-04,NaN,NaN,1.70,18.48,17.97,NaN,1.70,18.59,36.08,4.43,10.14,1.00,NaN,NaN
4,Ahmedabad,2015-01-05,NaN,NaN,22.10,21.42,37.76,NaN,22.10,39.33,39.31,7.01,18.89,2.78,NaN,NaN

In [7]:
df.duplicated().sum()

np.int64(0)

In [8]:
df.duplicated(subset = ["City" , "Date"]).sum()

np.int64(0)

In [9]:
df = df.drop(columns = ["Xylene" , "Toluene" , "Benzene"])

In [10]:
df.shape

(29531, 13)

In [11]:
df.columns

Index(['City', 'Date', 'PM2.5', 'PM10', 'NO', 'NO2', 'NOx', 'NH3', 'CO', 'SO2',
       'O3', 'AQI', 'AQI_Bucket'],
      dtype='str')

In [12]:
num_cols = df.select_dtypes(include = np.number).columns

(df[num_cols] < 0).sum()

PM2.5    0
PM10     0
NO       0
NO2      0
NOx      0
NH3      0
CO       0
SO2      0
O3       0
AQI      0
dtype: int64

In [13]:
city_coverage = df.groupby("City").agg(

    start_date = ("Date" , "min"),
    end_date = ("Date" , "max") , 
    records = ("Date" , "count")
)

city_coverage

                   start_date   end_date  records
City
Ahmedabad          2015-01-01 2020-07-01     2009
Aizawl             2020-03-11 2020-07-01      113
Amaravati          2017-11-24 2020-07-01      951
Amritsar           2017-02-27 2020-07-01     1221
Bengaluru          2015-01-01 2020-07-01     2009
Bhopal             2019-09-17 2020-07-01      289
Brajrajnagar       2017-12-07 2020-07-01      938
Chandigarh         2019-09-02 2020-07-01      304
Chennai            2015-01-01 2020-07-01     2009
Coimbatore         2019-06-12 2020-07-01      386
Delhi              2015-01-01 2020-07-01     2009
Ernakulam          2020-01-22 2020-07-01      162
Gurugram           2015-11-27 2020-07-01     1679
Guwahati           2019-02-16 2020-07-01      502
Hyderabad          2015-01-04 2020-07-01     2006
Jaipur             2017-06-14 2020-07-01     1114
Jorapokhar         2017-04-20 2020-07-01     1169
Kochi              2020-01-22 2020-07-01      162
Kolkata            2018-04-10 2020-07-01      814
Lucknow            2015-01-01 2020-07-01     2009
Mumbai             2015-01-01 2020-07-01     2009
Patna              2015-06-01 2020-07-01     1858
Shillong           2019-08-27 2020-07-01      310
Talcher            2017-12-20 2020-07-01      925
Thiruvananthapuram 2017-06-16 2020-07-01     1112
Visakhapatnam      2016-07-01 2020-07-01     1462

In [14]:
core_cols = ["PM2.5" , "PM10" , "NO2", "CO" , "SO2" , "O3" , "AQI"]

city_missing = (
    
    df.groupby("City")[core_cols]
    .apply(lambda x : x.isnull().mean() * 100)
    .round(2)
)

city_missing

                    PM2.5    PM10    NO2     CO    SO2      O3    AQI
City
Ahmedabad           31.26   79.74  30.26  30.31  31.86   34.10  33.60
Aizawl               1.77    0.88   0.00   0.00   0.00    7.96   1.77
Amaravati            6.20    5.78   5.78  10.20   6.83    5.78  11.57
Amritsar            10.48    5.16   3.60   6.22  13.76    9.42   7.78
Bengaluru            7.27   17.92   0.30   0.55   0.30    7.17   4.93
Bhopal               3.11    3.11   3.11   3.11   3.11    3.11   3.81
Brajrajnagar        19.72   18.44  24.95  15.99  20.58   21.64  23.99
Chandigarh           4.93    0.00   1.32   0.00   0.00    0.00   1.64
Chennai              5.82   84.97   1.79   1.24   1.79    2.44   6.22
Coimbatore           2.07    1.81   2.85   0.78   0.78    0.78  10.88
Delhi                0.10    3.83   0.10   0.00   5.48    4.18   0.50
Ernakulam            2.47    2.47  33.95   2.47   2.47  100.00   5.56
Gurugram             9.17   55.93   8.10   6.49  10.42    6.91  13.46
Guwahati             0.20    0.00   0.20   0.20   0.20    0.20   1.39
Hyderabad            5.73   17.70   1.40   0.25   1.30    1.30   6.28
Jaipur               1.08    1.26   1.26   0.63   1.08    1.35   1.80
Jorapokhar          67.58   23.52  23.10  43.88  30.03   25.15  34.05
Kochi                0.00    0.00   3.70   0.00   0.00    0.00   2.47
Kolkata              6.76    6.76   3.07   0.00   7.62    6.14   7.37
Lucknow              5.08  100.00   1.19   1.39   3.19    1.34   5.77
Mumbai              60.98   62.02  62.37   1.24  60.73   60.33  61.42
Patna               17.28   89.72  10.98   8.13  11.03   14.96  21.47
Shillong            20.65   22.26  19.03  10.65  17.42   18.06  33.87
Talcher             19.89   19.35  24.00  16.00  20.76   18.27  24.54
Thiruvananthapuram   3.78    3.42   2.79   1.44   2.79    2.79   5.40
Visakhapatnam       15.73   16.14  16.96   2.67  15.53   15.66  19.90

In [15]:
ml_features = ["PM2.5" , "NO2" , "CO" , "SO2" , "O3"]

quality = df.groupby("City").agg(
    
    records = ("Date" , "count") , 
    start_date = ("Date" , "min"),
    end_date = ("Date" , "max") , 
    aqi_missing = ("AQI" , lambda x : x.isna().mean() *100)
)

feature_missing = (
    
    df.groupby("City")[ml_features]
    .apply(lambda x : x.isna().mean().mean() * 100)
    .rename("feature_missing")
)

quality = quality.join(feature_missing)

quality = quality.round( {
    "aqi_missing" : 2,
    "feature_missing" : 2
})

quality.sort_values(["records"  , "aqi_missing"] , ascending = [False , True])

,records,start_date,end_date,aqi_missing,feature_missing
City,,,,,
Delhi,2009,2015-01-01,2020-07-01,0.50,1.97
Bengaluru,2009,2015-01-01,2020-07-01,4.93,3.12
Lucknow,2009,2015-01-01,2020-07-01,5.77,2.44
Chennai,2009,2015-01-01,2020-07-01,6.22,2.62
Ahmedabad,2009,2015-01-01,2020-07-01,33.60,31.56
Mumbai,2009,2015-01-01,2020-07-01,61.42,49.13
Hyderabad,2006,2015-01-04,2020-07-01,6.28,1.99
Patna,1858,2015-06-01,2020-07-01,21.47,12.48
Gurugram,1679,2015-11-27,2020-07-01,13.46,8.22
Visakhapatnam,1462,2016-07-01,2020-07-01,19.90,13.31
Amritsar,1221,2017-02-27,2020-07-01,7.78,8.70
Jorapokhar,1169,2017-04-20,2020-07-01,34.05,37.95
Jaipur,1114,2017-06-14,2020-07-01,1.80,1.08
Thiruvananthapuram,1112,2017-06-16,2020-07-01,5.40,2.72
Amaravati,951,2017-11-24,2020-07-01,11.57,6.96
Brajrajnagar,938,2017-12-07,2020-07-01,23.99,20.58
Talcher,925,2017-12-20,2020-07-01,24.54,19.78
Kolkata,814,2018-04-10,2020-07-01,7.37,4.72
Guwahati,502,2019-02-16,2020-07-01,1.39,0.20
Coimbatore,386,2019-06-12,2020-07-01,10.88,1.45
Shillong,310,2019-08-27,2020-07-01,33.87,17.16
Chandigarh,304,2019-09-02,2020-07-01,1.64,1.25
Bhopal,289,2019-09-17,2020-07-01,3.81,3.11
Kochi,162,2020-01-22,2020-07-01,2.47,0.74
Ernakulam,162,2020-01-22,2020-07-01,5.56,28.27
Aizawl,113,2020-03-11,2020-07-01,1.77,1.95

In [16]:
eligible_cities = quality[
    (quality["records"] >= 500) &
    (quality["aqi_missing"] <= 20) &
    (quality["feature_missing"] <= 25)
].index.tolist()

eligible_cities

['Amaravati',
 'Amritsar',
 'Bengaluru',
 'Chennai',
 'Delhi',
 'Gurugram',
 'Guwahati',
 'Hyderabad',
 'Jaipur',
 'Kolkata',
 'Lucknow',
 'Thiruvananthapuram',
 'Visakhapatnam']

In [17]:
df.to_csv(
    "../data/processed/air_quality_clean.csv",
    index=False
)

#### ML candidate dataset

In [18]:
ml_df = df[df["City"].isin(eligible_cities)].copy()

ml_df.shape

(18897, 13)

In [19]:
ml_df["City"].value_counts()

City
Bengaluru             2009
Chennai               2009
Delhi                 2009
Lucknow               2009
Hyderabad             2006
Gurugram              1679
Visakhapatnam         1462
Amritsar              1221
Jaipur                1114
Thiruvananthapuram    1112
Amaravati              951
Kolkata                814
Guwahati               502
Name: count, dtype: int64

In [20]:
def max_missing_streak(s):
    m = s.isna()
    groups = (m != m.shift()).cumsum()
    streaks = m.groupby(groups).sum()
    return int(streaks.max()) if len(streaks) else 0

In [21]:
check_cols = ["PM2.5", "NO2", "CO", "SO2", "O3", "AQI"]

streak_report = pd.DataFrame()

for col in check_cols:
    streak_report[col] = (
        ml_df.groupby("City")[col]
        .apply(max_missing_streak)
    )

streak_report

                    PM2.5  NO2  CO  SO2   O3  AQI
City
Amaravati              37   37  37   37   37   38
Amritsar               60    9  15   51   50   18
Bengaluru              78    2   2    2   23   79
Chennai                81   17  11   17   17   82
Delhi                   2    2   0   81   81    4
Gurugram               56   52  45   30   37   57
Guwahati                1    1   1    1    1    2
Hyderabad              86   19   1   19   19   86
Jaipur                  5    5   5    5    5    6
Kolkata                31   15   0   37   32   59
Lucknow                78   13  13   13   13   79
Thiruvananthapuram      9    9   7    9    9   29
Visakhapatnam         172  203   9  172  174  202

In [22]:
def date_gap_summary(g):
    g = g.sort_values("Date")
    gaps = g["Date"].diff().dt.days

    return pd.Series({
        "max_gap_days": gaps.max(),
        "missing_calendar_days": (
            (g["Date"].max() - g["Date"].min()).days + 1 - len(g)
        )
    })

date_gaps = (
    ml_df.groupby("City")
    .apply(date_gap_summary, include_groups=False) # type: ignore
) # type: ignore

date_gaps

                    max_gap_days  missing_calendar_days
City
Amaravati                    1.0                    0.0
Amritsar                     1.0                    0.0
Bengaluru                    1.0                    0.0
Chennai                      1.0                    0.0
Delhi                        1.0                    0.0
Gurugram                     1.0                    0.0
Guwahati                     1.0                    0.0
Hyderabad                    1.0                    0.0
Jaipur                       1.0                    0.0
Kolkata                      1.0                    0.0
Lucknow                      1.0                    0.0
Thiruvananthapuram           1.0                    0.0
Visakhapatnam                1.0                    0.0

In [23]:
ml_df = ml_df.sort_values(["City", "Date"]).reset_index(drop=True)

ml_df.to_csv(
    "../data/processed/ml_candidate.csv",
    index=False
)